### ISSUE TITLE
avoid cheking isempty() in main

### ISSUE THREAD

**Issue by kashyapan** [Kishy-nivas/data-structures-in-cpp#3]
In Stack and Queue you've been checking `isempty()` condition in `main() `

Why so? You could have checked them in ADT itself.

**Comment by Kishy-nivas** [comment]
In Stack and queue  adt in stl , you have to manually check isempty each time before accessing the element, accessing the empty stack or queue gives segmentation fault. cout<<" " in class implementation is usually a "no-no ' ;
